network:
  host: 0.0.0.0
cluster:
  name: docker-single-node-cluster
#  initial_master_nodes: elastics01
http:
  port: 9200
node:
  name: elastics01
  data: true
  ingest: true
  master: true
  max_local_storage_nodes: 1
path:
  data: /usr/share/elasticsearch/data
transport:
  tcp:
    port: 9300
xpack:
  license:
    self_generated.type: basic
  ml:
    use_auto_machine_memory_percent: true
  security:
    enabled: true
    http:
      ssl:
        enabled: true
        key: certs/elastics01/elastics01.key
        certificate: certs/elastics01/elastics01.crt
        verification_mode: certificate