network.host: 0.0.0.0
cluster.name: docker-single-node-cluster
http.port: 9200
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: yokohama
path.data: /usr/share/elasticsearch/data
transport.tcp.port: 9300
xpack.license.self_generated.type: basic
xpack.security.enabled: true