version: '3'

services:
  elasticsearch:
    container_name: elasticsearch-service
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes: 
      - ./data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    labels:
      ELK_STACK: "true"
    networks:
      default:
        aliases:
          - elasticsearch
  kibana-service:
    container_name: kibana-service
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports: 
      - 5601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config/
    labels:
      ELK_STACK: "true"
    depends_on: 
      - elasticsearch