version: '3'

services:
  filebeat:
    container_name: filebeat_agent
    image: docker.elastic.co/beats/filebeat:7.10.2
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    labels:
      ELK_STACK: "true"
    